export const MAX_CHAT_USER_MESSAGE_CHARACTERS = 2_000;
export const MAX_CHAT_HISTORY_TEXT_CHARACTERS = 12_000;
export const MAX_CHAT_HISTORY_USER_MESSAGES = 12;
export const MAX_AI_OUTPUT_TOKENS = 2_048;
export const MAX_AI_BUFFERED_TEXT_CHARACTERS = 16_000;
export const MAX_AI_TOOL_STEPS = 5;
