/**
 * 全球国家基础目录 —— ADR-040 / ADR-015 C 层。
 *
 * 派生自 Natural Earth `ne_110m_admin_0_countries`（公共领域，修订
 * ca96624a56bd078437bca8184e78163e5039ad19，与 public/geo/README.md 同一来源）。
 * `iso2`/`regionCode`/`subregionCode` 取自 Natural Earth 的 ISO_A2 / REGION_UN /
 * SUBREGION；`nameEn` 与 public/geo/world-countries-index.json 完全一致。
 * 目录只包含名称与区域归类，不包含法规、市场或产品事实，不得作为真实
 * 法规或销售依据（ADR-016）。
 *
 * 确定性静态数据：178 行；Liechtenstein 与 Malta 使用同一固定修订的 1:10m
 * 几何，Mauritius 是法规覆盖新增但尚无地图几何的目录项。
 * 并同步 tests/integration/database.test.ts 与 tests/map-data.test.ts 的断言。
 */

export interface CountryCatalogEntry {
  readonly iso2: string;
  readonly iso3: string;
  readonly nameEn: string;
  readonly regionCode: string;
  readonly subregionCode: string;
}

/**
 * ADR-015 分层覆盖目标（A1 深度样板 + A2 深度扩展 + B 主流摘要），
 * 种子覆盖状态为 `planned`；其余目录国家为 `no_data`。
 */
export const plannedCoverageIso3: ReadonlySet<string> = new Set([
  // A1 深度样板
  "BRA",
  "CHN",
  "DEU",
  "IND",
  "USA",
  // A2 深度扩展
  "AUS",
  "JPN",
  "KOR",
  "MEX",
  "TUR",
  // B 主流摘要
  "ARE",
  "ARG",
  "CAN",
  "CHE",
  "ESP",
  "FRA",
  "GBR",
  "IDN",
  "ITA",
  "MYS",
  "POL",
  "RUS",
  "SAU",
  "SGP",
  "THA",
  "VNM",
  "ZAF",
  "LIE",
  "MLT",
]);

export const countryCatalog: readonly CountryCatalogEntry[] = [
  { iso2: "AF", iso3: "AFG", nameEn: "Afghanistan", regionCode: "ASIA", subregionCode: "SOUTHERN_ASIA" },
  { iso2: "AO", iso3: "AGO", nameEn: "Angola", regionCode: "AFRICA", subregionCode: "MIDDLE_AFRICA" },
  { iso2: "AL", iso3: "ALB", nameEn: "Albania", regionCode: "EUROPE", subregionCode: "SOUTHERN_EUROPE" },
  { iso2: "AE", iso3: "ARE", nameEn: "United Arab Emirates", regionCode: "ASIA", subregionCode: "WESTERN_ASIA" },
  { iso2: "AR", iso3: "ARG", nameEn: "Argentina", regionCode: "AMERICAS", subregionCode: "SOUTH_AMERICA" },
  { iso2: "AM", iso3: "ARM", nameEn: "Armenia", regionCode: "ASIA", subregionCode: "WESTERN_ASIA" },
  { iso2: "AQ", iso3: "ATA", nameEn: "Antarctica", regionCode: "ANTARCTICA", subregionCode: "ANTARCTICA" },
  { iso2: "TF", iso3: "ATF", nameEn: "French Southern and Antarctic Lands", regionCode: "AFRICA", subregionCode: "SEVEN_SEAS_OPEN_OCEAN" },
  { iso2: "AU", iso3: "AUS", nameEn: "Australia", regionCode: "OCEANIA", subregionCode: "AUSTRALIA_AND_NEW_ZEALAND" },
  { iso2: "AT", iso3: "AUT", nameEn: "Austria", regionCode: "EUROPE", subregionCode: "WESTERN_EUROPE" },
  { iso2: "AZ", iso3: "AZE", nameEn: "Azerbaijan", regionCode: "ASIA", subregionCode: "WESTERN_ASIA" },
  { iso2: "BI", iso3: "BDI", nameEn: "Burundi", regionCode: "AFRICA", subregionCode: "EASTERN_AFRICA" },
  { iso2: "BE", iso3: "BEL", nameEn: "Belgium", regionCode: "EUROPE", subregionCode: "WESTERN_EUROPE" },
  { iso2: "BJ", iso3: "BEN", nameEn: "Benin", regionCode: "AFRICA", subregionCode: "WESTERN_AFRICA" },
  { iso2: "BF", iso3: "BFA", nameEn: "Burkina Faso", regionCode: "AFRICA", subregionCode: "WESTERN_AFRICA" },
  { iso2: "BD", iso3: "BGD", nameEn: "Bangladesh", regionCode: "ASIA", subregionCode: "SOUTHERN_ASIA" },
  { iso2: "BG", iso3: "BGR", nameEn: "Bulgaria", regionCode: "EUROPE", subregionCode: "EASTERN_EUROPE" },
  { iso2: "BS", iso3: "BHS", nameEn: "The Bahamas", regionCode: "AMERICAS", subregionCode: "CARIBBEAN" },
  { iso2: "BA", iso3: "BIH", nameEn: "Bosnia and Herzegovina", regionCode: "EUROPE", subregionCode: "SOUTHERN_EUROPE" },
  { iso2: "BY", iso3: "BLR", nameEn: "Belarus", regionCode: "EUROPE", subregionCode: "EASTERN_EUROPE" },
  { iso2: "BZ", iso3: "BLZ", nameEn: "Belize", regionCode: "AMERICAS", subregionCode: "CENTRAL_AMERICA" },
  { iso2: "BO", iso3: "BOL", nameEn: "Bolivia", regionCode: "AMERICAS", subregionCode: "SOUTH_AMERICA" },
  { iso2: "BR", iso3: "BRA", nameEn: "Brazil", regionCode: "AMERICAS", subregionCode: "SOUTH_AMERICA" },
  { iso2: "BN", iso3: "BRN", nameEn: "Brunei", regionCode: "ASIA", subregionCode: "SOUTH_EASTERN_ASIA" },
  { iso2: "BT", iso3: "BTN", nameEn: "Bhutan", regionCode: "ASIA", subregionCode: "SOUTHERN_ASIA" },
  { iso2: "BW", iso3: "BWA", nameEn: "Botswana", regionCode: "AFRICA", subregionCode: "SOUTHERN_AFRICA" },
  { iso2: "CF", iso3: "CAF", nameEn: "Central African Republic", regionCode: "AFRICA", subregionCode: "MIDDLE_AFRICA" },
  { iso2: "CA", iso3: "CAN", nameEn: "Canada", regionCode: "AMERICAS", subregionCode: "NORTHERN_AMERICA" },
  { iso2: "CH", iso3: "CHE", nameEn: "Switzerland", regionCode: "EUROPE", subregionCode: "WESTERN_EUROPE" },
  { iso2: "CL", iso3: "CHL", nameEn: "Chile", regionCode: "AMERICAS", subregionCode: "SOUTH_AMERICA" },
  { iso2: "CN", iso3: "CHN", nameEn: "People's Republic of China", regionCode: "ASIA", subregionCode: "EASTERN_ASIA" },
  { iso2: "CI", iso3: "CIV", nameEn: "Ivory Coast", regionCode: "AFRICA", subregionCode: "WESTERN_AFRICA" },
  { iso2: "CM", iso3: "CMR", nameEn: "Cameroon", regionCode: "AFRICA", subregionCode: "MIDDLE_AFRICA" },
  { iso2: "CD", iso3: "COD", nameEn: "Democratic Republic of the Congo", regionCode: "AFRICA", subregionCode: "MIDDLE_AFRICA" },
  { iso2: "CG", iso3: "COG", nameEn: "Republic of the Congo", regionCode: "AFRICA", subregionCode: "MIDDLE_AFRICA" },
  { iso2: "CO", iso3: "COL", nameEn: "Colombia", regionCode: "AMERICAS", subregionCode: "SOUTH_AMERICA" },
  { iso2: "CR", iso3: "CRI", nameEn: "Costa Rica", regionCode: "AMERICAS", subregionCode: "CENTRAL_AMERICA" },
  { iso2: "CU", iso3: "CUB", nameEn: "Cuba", regionCode: "AMERICAS", subregionCode: "CARIBBEAN" },
  { iso2: "CY", iso3: "CYP", nameEn: "Cyprus", regionCode: "ASIA", subregionCode: "WESTERN_ASIA" },
  { iso2: "CZ", iso3: "CZE", nameEn: "Czech Republic", regionCode: "EUROPE", subregionCode: "EASTERN_EUROPE" },
  { iso2: "DE", iso3: "DEU", nameEn: "Germany", regionCode: "EUROPE", subregionCode: "WESTERN_EUROPE" },
  { iso2: "DJ", iso3: "DJI", nameEn: "Djibouti", regionCode: "AFRICA", subregionCode: "EASTERN_AFRICA" },
  { iso2: "DK", iso3: "DNK", nameEn: "Denmark", regionCode: "EUROPE", subregionCode: "NORTHERN_EUROPE" },
  { iso2: "DO", iso3: "DOM", nameEn: "Dominican Republic", regionCode: "AMERICAS", subregionCode: "CARIBBEAN" },
  { iso2: "DZ", iso3: "DZA", nameEn: "Algeria", regionCode: "AFRICA", subregionCode: "NORTHERN_AFRICA" },
  { iso2: "EC", iso3: "ECU", nameEn: "Ecuador", regionCode: "AMERICAS", subregionCode: "SOUTH_AMERICA" },
  { iso2: "EG", iso3: "EGY", nameEn: "Egypt", regionCode: "AFRICA", subregionCode: "NORTHERN_AFRICA" },
  { iso2: "ER", iso3: "ERI", nameEn: "Eritrea", regionCode: "AFRICA", subregionCode: "EASTERN_AFRICA" },
  { iso2: "EH", iso3: "ESH", nameEn: "Western Sahara", regionCode: "AFRICA", subregionCode: "NORTHERN_AFRICA" },
  { iso2: "ES", iso3: "ESP", nameEn: "Spain", regionCode: "EUROPE", subregionCode: "SOUTHERN_EUROPE" },
  { iso2: "EE", iso3: "EST", nameEn: "Estonia", regionCode: "EUROPE", subregionCode: "NORTHERN_EUROPE" },
  { iso2: "ET", iso3: "ETH", nameEn: "Ethiopia", regionCode: "AFRICA", subregionCode: "EASTERN_AFRICA" },
  { iso2: "FI", iso3: "FIN", nameEn: "Finland", regionCode: "EUROPE", subregionCode: "NORTHERN_EUROPE" },
  { iso2: "FJ", iso3: "FJI", nameEn: "Fiji", regionCode: "OCEANIA", subregionCode: "MELANESIA" },
  { iso2: "FK", iso3: "FLK", nameEn: "Falkland Islands", regionCode: "AMERICAS", subregionCode: "SOUTH_AMERICA" },
  { iso2: "FR", iso3: "FRA", nameEn: "France", regionCode: "EUROPE", subregionCode: "WESTERN_EUROPE" },
  { iso2: "GA", iso3: "GAB", nameEn: "Gabon", regionCode: "AFRICA", subregionCode: "MIDDLE_AFRICA" },
  { iso2: "GB", iso3: "GBR", nameEn: "United Kingdom", regionCode: "EUROPE", subregionCode: "NORTHERN_EUROPE" },
  { iso2: "GE", iso3: "GEO", nameEn: "Georgia", regionCode: "ASIA", subregionCode: "WESTERN_ASIA" },
  { iso2: "GH", iso3: "GHA", nameEn: "Ghana", regionCode: "AFRICA", subregionCode: "WESTERN_AFRICA" },
  { iso2: "GN", iso3: "GIN", nameEn: "Guinea", regionCode: "AFRICA", subregionCode: "WESTERN_AFRICA" },
  { iso2: "GM", iso3: "GMB", nameEn: "The Gambia", regionCode: "AFRICA", subregionCode: "WESTERN_AFRICA" },
  { iso2: "GW", iso3: "GNB", nameEn: "Guinea-Bissau", regionCode: "AFRICA", subregionCode: "WESTERN_AFRICA" },
  { iso2: "GQ", iso3: "GNQ", nameEn: "Equatorial Guinea", regionCode: "AFRICA", subregionCode: "MIDDLE_AFRICA" },
  { iso2: "GR", iso3: "GRC", nameEn: "Greece", regionCode: "EUROPE", subregionCode: "SOUTHERN_EUROPE" },
  { iso2: "GL", iso3: "GRL", nameEn: "Greenland", regionCode: "AMERICAS", subregionCode: "NORTHERN_AMERICA" },
  { iso2: "GT", iso3: "GTM", nameEn: "Guatemala", regionCode: "AMERICAS", subregionCode: "CENTRAL_AMERICA" },
  { iso2: "GY", iso3: "GUY", nameEn: "Guyana", regionCode: "AMERICAS", subregionCode: "SOUTH_AMERICA" },
  { iso2: "HN", iso3: "HND", nameEn: "Honduras", regionCode: "AMERICAS", subregionCode: "CENTRAL_AMERICA" },
  { iso2: "HR", iso3: "HRV", nameEn: "Croatia", regionCode: "EUROPE", subregionCode: "SOUTHERN_EUROPE" },
  { iso2: "HT", iso3: "HTI", nameEn: "Haiti", regionCode: "AMERICAS", subregionCode: "CARIBBEAN" },
  { iso2: "HU", iso3: "HUN", nameEn: "Hungary", regionCode: "EUROPE", subregionCode: "EASTERN_EUROPE" },
  { iso2: "ID", iso3: "IDN", nameEn: "Indonesia", regionCode: "ASIA", subregionCode: "SOUTH_EASTERN_ASIA" },
  { iso2: "IN", iso3: "IND", nameEn: "India", regionCode: "ASIA", subregionCode: "SOUTHERN_ASIA" },
  { iso2: "IE", iso3: "IRL", nameEn: "Ireland", regionCode: "EUROPE", subregionCode: "NORTHERN_EUROPE" },
  { iso2: "IR", iso3: "IRN", nameEn: "Iran", regionCode: "ASIA", subregionCode: "SOUTHERN_ASIA" },
  { iso2: "IQ", iso3: "IRQ", nameEn: "Iraq", regionCode: "ASIA", subregionCode: "WESTERN_ASIA" },
  { iso2: "IS", iso3: "ISL", nameEn: "Iceland", regionCode: "EUROPE", subregionCode: "NORTHERN_EUROPE" },
  { iso2: "IL", iso3: "ISR", nameEn: "Israel", regionCode: "ASIA", subregionCode: "WESTERN_ASIA" },
  { iso2: "IT", iso3: "ITA", nameEn: "Italy", regionCode: "EUROPE", subregionCode: "SOUTHERN_EUROPE" },
  { iso2: "JM", iso3: "JAM", nameEn: "Jamaica", regionCode: "AMERICAS", subregionCode: "CARIBBEAN" },
  { iso2: "JO", iso3: "JOR", nameEn: "Jordan", regionCode: "ASIA", subregionCode: "WESTERN_ASIA" },
  { iso2: "JP", iso3: "JPN", nameEn: "Japan", regionCode: "ASIA", subregionCode: "EASTERN_ASIA" },
  { iso2: "KZ", iso3: "KAZ", nameEn: "Kazakhstan", regionCode: "ASIA", subregionCode: "CENTRAL_ASIA" },
  { iso2: "KE", iso3: "KEN", nameEn: "Kenya", regionCode: "AFRICA", subregionCode: "EASTERN_AFRICA" },
  { iso2: "KG", iso3: "KGZ", nameEn: "Kyrgyzstan", regionCode: "ASIA", subregionCode: "CENTRAL_ASIA" },
  { iso2: "KH", iso3: "KHM", nameEn: "Cambodia", regionCode: "ASIA", subregionCode: "SOUTH_EASTERN_ASIA" },
  { iso2: "KR", iso3: "KOR", nameEn: "South Korea", regionCode: "ASIA", subregionCode: "EASTERN_ASIA" },
  { iso2: "KW", iso3: "KWT", nameEn: "Kuwait", regionCode: "ASIA", subregionCode: "WESTERN_ASIA" },
  { iso2: "LA", iso3: "LAO", nameEn: "Laos", regionCode: "ASIA", subregionCode: "SOUTH_EASTERN_ASIA" },
  { iso2: "LB", iso3: "LBN", nameEn: "Lebanon", regionCode: "ASIA", subregionCode: "WESTERN_ASIA" },
  { iso2: "LR", iso3: "LBR", nameEn: "Liberia", regionCode: "AFRICA", subregionCode: "WESTERN_AFRICA" },
  { iso2: "LY", iso3: "LBY", nameEn: "Libya", regionCode: "AFRICA", subregionCode: "NORTHERN_AFRICA" },
  { iso2: "LK", iso3: "LKA", nameEn: "Sri Lanka", regionCode: "ASIA", subregionCode: "SOUTHERN_ASIA" },
  { iso2: "LS", iso3: "LSO", nameEn: "Lesotho", regionCode: "AFRICA", subregionCode: "SOUTHERN_AFRICA" },
  { iso2: "LT", iso3: "LTU", nameEn: "Lithuania", regionCode: "EUROPE", subregionCode: "NORTHERN_EUROPE" },
  { iso2: "LI", iso3: "LIE", nameEn: "Liechtenstein", regionCode: "EUROPE", subregionCode: "WESTERN_EUROPE" },
  { iso2: "LU", iso3: "LUX", nameEn: "Luxembourg", regionCode: "EUROPE", subregionCode: "WESTERN_EUROPE" },
  { iso2: "LV", iso3: "LVA", nameEn: "Latvia", regionCode: "EUROPE", subregionCode: "NORTHERN_EUROPE" },
  { iso2: "MA", iso3: "MAR", nameEn: "Morocco", regionCode: "AFRICA", subregionCode: "NORTHERN_AFRICA" },
  { iso2: "MD", iso3: "MDA", nameEn: "Moldova", regionCode: "EUROPE", subregionCode: "EASTERN_EUROPE" },
  { iso2: "MG", iso3: "MDG", nameEn: "Madagascar", regionCode: "AFRICA", subregionCode: "EASTERN_AFRICA" },
  { iso2: "MX", iso3: "MEX", nameEn: "Mexico", regionCode: "AMERICAS", subregionCode: "CENTRAL_AMERICA" },
  { iso2: "MK", iso3: "MKD", nameEn: "North Macedonia", regionCode: "EUROPE", subregionCode: "SOUTHERN_EUROPE" },
  { iso2: "ML", iso3: "MLI", nameEn: "Mali", regionCode: "AFRICA", subregionCode: "WESTERN_AFRICA" },
  { iso2: "MT", iso3: "MLT", nameEn: "Malta", regionCode: "EUROPE", subregionCode: "SOUTHERN_EUROPE" },
  { iso2: "MM", iso3: "MMR", nameEn: "Myanmar", regionCode: "ASIA", subregionCode: "SOUTH_EASTERN_ASIA" },
  { iso2: "ME", iso3: "MNE", nameEn: "Montenegro", regionCode: "EUROPE", subregionCode: "SOUTHERN_EUROPE" },
  { iso2: "MN", iso3: "MNG", nameEn: "Mongolia", regionCode: "ASIA", subregionCode: "EASTERN_ASIA" },
  { iso2: "MZ", iso3: "MOZ", nameEn: "Mozambique", regionCode: "AFRICA", subregionCode: "EASTERN_AFRICA" },
  { iso2: "MR", iso3: "MRT", nameEn: "Mauritania", regionCode: "AFRICA", subregionCode: "WESTERN_AFRICA" },
  { iso2: "MU", iso3: "MUS", nameEn: "Mauritius", regionCode: "AFRICA", subregionCode: "EASTERN_AFRICA" },
  { iso2: "MW", iso3: "MWI", nameEn: "Malawi", regionCode: "AFRICA", subregionCode: "EASTERN_AFRICA" },
  { iso2: "MY", iso3: "MYS", nameEn: "Malaysia", regionCode: "ASIA", subregionCode: "SOUTH_EASTERN_ASIA" },
  { iso2: "NA", iso3: "NAM", nameEn: "Namibia", regionCode: "AFRICA", subregionCode: "SOUTHERN_AFRICA" },
  { iso2: "NC", iso3: "NCL", nameEn: "New Caledonia", regionCode: "OCEANIA", subregionCode: "MELANESIA" },
  { iso2: "NE", iso3: "NER", nameEn: "Niger", regionCode: "AFRICA", subregionCode: "WESTERN_AFRICA" },
  { iso2: "NG", iso3: "NGA", nameEn: "Nigeria", regionCode: "AFRICA", subregionCode: "WESTERN_AFRICA" },
  { iso2: "NI", iso3: "NIC", nameEn: "Nicaragua", regionCode: "AMERICAS", subregionCode: "CENTRAL_AMERICA" },
  { iso2: "NL", iso3: "NLD", nameEn: "Netherlands", regionCode: "EUROPE", subregionCode: "WESTERN_EUROPE" },
  { iso2: "NO", iso3: "NOR", nameEn: "Norway", regionCode: "EUROPE", subregionCode: "NORTHERN_EUROPE" },
  { iso2: "NP", iso3: "NPL", nameEn: "Nepal", regionCode: "ASIA", subregionCode: "SOUTHERN_ASIA" },
  { iso2: "NZ", iso3: "NZL", nameEn: "New Zealand", regionCode: "OCEANIA", subregionCode: "AUSTRALIA_AND_NEW_ZEALAND" },
  { iso2: "OM", iso3: "OMN", nameEn: "Oman", regionCode: "ASIA", subregionCode: "WESTERN_ASIA" },
  { iso2: "PK", iso3: "PAK", nameEn: "Pakistan", regionCode: "ASIA", subregionCode: "SOUTHERN_ASIA" },
  { iso2: "PA", iso3: "PAN", nameEn: "Panama", regionCode: "AMERICAS", subregionCode: "CENTRAL_AMERICA" },
  { iso2: "PE", iso3: "PER", nameEn: "Peru", regionCode: "AMERICAS", subregionCode: "SOUTH_AMERICA" },
  { iso2: "PH", iso3: "PHL", nameEn: "Philippines", regionCode: "ASIA", subregionCode: "SOUTH_EASTERN_ASIA" },
  { iso2: "PG", iso3: "PNG", nameEn: "Papua New Guinea", regionCode: "OCEANIA", subregionCode: "MELANESIA" },
  { iso2: "PL", iso3: "POL", nameEn: "Poland", regionCode: "EUROPE", subregionCode: "EASTERN_EUROPE" },
  { iso2: "PR", iso3: "PRI", nameEn: "Puerto Rico", regionCode: "AMERICAS", subregionCode: "CARIBBEAN" },
  { iso2: "KP", iso3: "PRK", nameEn: "North Korea", regionCode: "ASIA", subregionCode: "EASTERN_ASIA" },
  { iso2: "PT", iso3: "PRT", nameEn: "Portugal", regionCode: "EUROPE", subregionCode: "SOUTHERN_EUROPE" },
  { iso2: "PY", iso3: "PRY", nameEn: "Paraguay", regionCode: "AMERICAS", subregionCode: "SOUTH_AMERICA" },
  { iso2: "PS", iso3: "PSE", nameEn: "Palestine", regionCode: "ASIA", subregionCode: "WESTERN_ASIA" },
  { iso2: "QA", iso3: "QAT", nameEn: "Qatar", regionCode: "ASIA", subregionCode: "WESTERN_ASIA" },
  { iso2: "RO", iso3: "ROU", nameEn: "Romania", regionCode: "EUROPE", subregionCode: "EASTERN_EUROPE" },
  { iso2: "RU", iso3: "RUS", nameEn: "Russia", regionCode: "EUROPE", subregionCode: "EASTERN_EUROPE" },
  { iso2: "RW", iso3: "RWA", nameEn: "Rwanda", regionCode: "AFRICA", subregionCode: "EASTERN_AFRICA" },
  { iso2: "SA", iso3: "SAU", nameEn: "Saudi Arabia", regionCode: "ASIA", subregionCode: "WESTERN_ASIA" },
  { iso2: "SD", iso3: "SDN", nameEn: "Sudan", regionCode: "AFRICA", subregionCode: "NORTHERN_AFRICA" },
  { iso2: "SN", iso3: "SEN", nameEn: "Senegal", regionCode: "AFRICA", subregionCode: "WESTERN_AFRICA" },
  { iso2: "SB", iso3: "SLB", nameEn: "Solomon Islands", regionCode: "OCEANIA", subregionCode: "MELANESIA" },
  { iso2: "SL", iso3: "SLE", nameEn: "Sierra Leone", regionCode: "AFRICA", subregionCode: "WESTERN_AFRICA" },
  { iso2: "SV", iso3: "SLV", nameEn: "El Salvador", regionCode: "AMERICAS", subregionCode: "CENTRAL_AMERICA" },
  { iso2: "SO", iso3: "SOM", nameEn: "Somalia", regionCode: "AFRICA", subregionCode: "EASTERN_AFRICA" },
  { iso2: "RS", iso3: "SRB", nameEn: "Serbia", regionCode: "EUROPE", subregionCode: "SOUTHERN_EUROPE" },
  { iso2: "SS", iso3: "SSD", nameEn: "South Sudan", regionCode: "AFRICA", subregionCode: "EASTERN_AFRICA" },
  { iso2: "SR", iso3: "SUR", nameEn: "Suriname", regionCode: "AMERICAS", subregionCode: "SOUTH_AMERICA" },
  { iso2: "SK", iso3: "SVK", nameEn: "Slovakia", regionCode: "EUROPE", subregionCode: "EASTERN_EUROPE" },
  { iso2: "SI", iso3: "SVN", nameEn: "Slovenia", regionCode: "EUROPE", subregionCode: "SOUTHERN_EUROPE" },
  { iso2: "SE", iso3: "SWE", nameEn: "Sweden", regionCode: "EUROPE", subregionCode: "NORTHERN_EUROPE" },
  { iso2: "SG", iso3: "SGP", nameEn: "Singapore", regionCode: "ASIA", subregionCode: "SOUTH_EASTERN_ASIA" },
  { iso2: "SZ", iso3: "SWZ", nameEn: "Eswatini", regionCode: "AFRICA", subregionCode: "SOUTHERN_AFRICA" },
  { iso2: "SY", iso3: "SYR", nameEn: "Syria", regionCode: "ASIA", subregionCode: "WESTERN_ASIA" },
  { iso2: "TD", iso3: "TCD", nameEn: "Chad", regionCode: "AFRICA", subregionCode: "MIDDLE_AFRICA" },
  { iso2: "TG", iso3: "TGO", nameEn: "Togo", regionCode: "AFRICA", subregionCode: "WESTERN_AFRICA" },
  { iso2: "TH", iso3: "THA", nameEn: "Thailand", regionCode: "ASIA", subregionCode: "SOUTH_EASTERN_ASIA" },
  { iso2: "TJ", iso3: "TJK", nameEn: "Tajikistan", regionCode: "ASIA", subregionCode: "CENTRAL_ASIA" },
  { iso2: "TM", iso3: "TKM", nameEn: "Turkmenistan", regionCode: "ASIA", subregionCode: "CENTRAL_ASIA" },
  { iso2: "TL", iso3: "TLS", nameEn: "East Timor", regionCode: "ASIA", subregionCode: "SOUTH_EASTERN_ASIA" },
  { iso2: "TT", iso3: "TTO", nameEn: "Trinidad and Tobago", regionCode: "AMERICAS", subregionCode: "CARIBBEAN" },
  { iso2: "TN", iso3: "TUN", nameEn: "Tunisia", regionCode: "AFRICA", subregionCode: "NORTHERN_AFRICA" },
  { iso2: "TR", iso3: "TUR", nameEn: "Turkey", regionCode: "ASIA", subregionCode: "WESTERN_ASIA" },
  { iso2: "TW", iso3: "TWN", nameEn: "Taiwan", regionCode: "ASIA", subregionCode: "EASTERN_ASIA" },
  { iso2: "TZ", iso3: "TZA", nameEn: "Tanzania", regionCode: "AFRICA", subregionCode: "EASTERN_AFRICA" },
  { iso2: "UG", iso3: "UGA", nameEn: "Uganda", regionCode: "AFRICA", subregionCode: "EASTERN_AFRICA" },
  { iso2: "UA", iso3: "UKR", nameEn: "Ukraine", regionCode: "EUROPE", subregionCode: "EASTERN_EUROPE" },
  { iso2: "UY", iso3: "URY", nameEn: "Uruguay", regionCode: "AMERICAS", subregionCode: "SOUTH_AMERICA" },
  { iso2: "US", iso3: "USA", nameEn: "United States of America", regionCode: "AMERICAS", subregionCode: "NORTHERN_AMERICA" },
  { iso2: "UZ", iso3: "UZB", nameEn: "Uzbekistan", regionCode: "ASIA", subregionCode: "CENTRAL_ASIA" },
  { iso2: "VE", iso3: "VEN", nameEn: "Venezuela", regionCode: "AMERICAS", subregionCode: "SOUTH_AMERICA" },
  { iso2: "VN", iso3: "VNM", nameEn: "Vietnam", regionCode: "ASIA", subregionCode: "SOUTH_EASTERN_ASIA" },
  { iso2: "VU", iso3: "VUT", nameEn: "Vanuatu", regionCode: "OCEANIA", subregionCode: "MELANESIA" },
  { iso2: "YE", iso3: "YEM", nameEn: "Yemen", regionCode: "ASIA", subregionCode: "WESTERN_ASIA" },
  { iso2: "ZA", iso3: "ZAF", nameEn: "South Africa", regionCode: "AFRICA", subregionCode: "SOUTHERN_AFRICA" },
  { iso2: "ZM", iso3: "ZMB", nameEn: "Zambia", regionCode: "AFRICA", subregionCode: "EASTERN_AFRICA" },
  { iso2: "ZW", iso3: "ZWE", nameEn: "Zimbabwe", regionCode: "AFRICA", subregionCode: "EASTERN_AFRICA" },
];
